# Generated by Django 4.2.6 on 2023-10-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
        ),
    ]
