# Generated by Django 4.2.6 on 2023-10-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aroduct_accessories',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_accessories', to='product.product_accessories', verbose_name='product_accessories'),
        ),
    ]
