# Generated by Django 4.2.6 on 2023-10-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_aroduct_accessories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='aroduct_accessories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.productcategory', verbose_name='category'),
        ),
    ]
