# Generated by Django 4.2.6 on 2023-10-15 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_info'),
        ('product', '0014_remove_product_aroduct_accessories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='settings.brand', verbose_name='Brand '),
        ),
    ]
