# Generated by Django 4.2.6 on 2023-10-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='CATParent',
        ),
    ]
