# Generated by Django 4.2.6 on 2023-10-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_subcategory_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
