# Generated by Django 4.2.6 on 2023-10-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Accessories',
        ),
    ]
