# Generated by Django 4.2.6 on 2023-10-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_delete_product_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Product Accessories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(default='', related_name='product_accessories', to='product.product_accessory', verbose_name='accessories'),
        ),
    ]
