# Generated by Django 4.2.6 on 2023-10-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_product_accessory_product_accessories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_alternative',
            name='PALNAlternatives',
        ),
        migrations.RemoveField(
            model_name='product_alternative',
            name='PALNProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='accessories',
        ),
        migrations.DeleteModel(
            name='Product_Accessory',
        ),
        migrations.DeleteModel(
            name='Product_Alternative',
        ),
    ]
