# Generated by Django 4.2.6 on 2023-10-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_order_orderitem_order_products_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ManyToManyField(to='product.color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ManyToManyField(to='product.size'),
        ),
    ]
