# Generated by Django 4.2.6 on 2023-10-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_cartitem_color_remove_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_color1', to='product.color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_size1', to='product.size'),
        ),
    ]
