# Generated by Django 4.2.6 on 2023-10-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_cartitem_color_cartitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
    ]
