# Generated by Django 4.2.6 on 2023-10-22 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0037_product_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='product_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
