# Generated by Django 4.2.6 on 2023-11-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cartitem_user_remove_cartitem_variations_and_more'),
        ('product', '0042_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
