# Generated by Django 4.2.6 on 2023-11-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
