# Generated by Django 4.2.6 on 2023-12-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
