# Generated by Django 4.2.6 on 2023-12-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
