# Generated by Django 4.2.6 on 2023-11-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_variation'),
        ('carts', '0004_remove_cartitem_user_remove_cartitem_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='product.variation'),
        ),
    ]
