# Generated by Django 4.2.6 on 2023-12-17 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0006_remove_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
