# Generated by Django 4.2.6 on 2023-12-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_number',
            field=models.IntegerField(default=0),
        ),
    ]
