# Generated by Django 4.2.6 on 2023-12-17 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0008_coupon_max_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
