# Generated by Django 4.2.6 on 2023-12-17 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_remove_coupon_expiration_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
