# Generated by Django 4.2.6 on 2023-12-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mode_of_contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='question_categories',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
