# Generated by Django 4.2.6 on 2023-10-16 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 10, 16, 13, 44, 38, 597110, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'NewsLitter',
                'verbose_name_plural': 'NewsLitter',
            },
        ),
    ]
