# Generated by Django 4.2.6 on 2023-10-16 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_newslitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslitter',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newslitter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 14, 4, 57, 882663, tzinfo=datetime.timezone.utc)),
        ),
    ]
