# Generated by Django 4.2.6 on 2023-10-16 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_newslitter_name_alter_newslitter_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='newslitter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 14, 35, 20, 12268, tzinfo=datetime.timezone.utc)),
        ),
    ]
