# Generated by Django 4.2.6 on 2023-10-16 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_brand_image_alter_newslitter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslitter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 15, 11, 52, 111774, tzinfo=datetime.timezone.utc)),
        ),
    ]
