# Generated by Django 4.2.6 on 2023-10-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_alter_newslitter_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslitter',
            name='name',
        ),
    ]
